spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testDb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: INFO