server:
  port: 8082

spring:
  application:
    name: userService
  profiles:
    active: dev

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
        globally_quoted_identifiers: true
