spring:
  application:
    name: user-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

  data:
    redis:
      host: 11.111.11.11
      port: 6666
      password: ci-secret
      database: 123

dbcp2:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    initial-size: 5
    max-total: 5
    max-idle: 5
    min-idle: 5
    between-eviction-millis: 300000
    min-evictable-idle-millis: 600000
    num-tests-per-eviction-run: 3


server:
  port: 10386
  shutdown: graceful

eureka:
  client:
    enabled: false

jwt:
  secret-key: "01234567890123456789012345678901"

# Order Payment
order:
  api:
    url: http://localhost:10392

# Book
book:
  api:
    url: http://localhost:10390

# Coupon
coupon:
  api:
    url: http://localhost:10388
