spring:
  application:
    name: user-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

server:
  shutdown: graceful

eureka:
  client:
    enabled: false
