INSERT INTO user_grade (grade_id,
                        grade_name,
                        reward_rate)
VALUES (1,
        'Standard',
        0.01);

INSERT INTO users (user_password,
                   user_username,
                   user_name,
                   user_email,
                   nickname,
                   user_phone,
                   user_birth,
                   user_create_at,
                   user_last_login_at,
                   points,
                   user_role,
                   user_state,
                   provider_id,
                   provider_name,
                   grade_id)
VALUES ('$2a$10$gbnVwLK04mxMpf5Za.cbae9DUUqLIEYea1uv18AbKSU.YucNi.BoK',
        '1',
        '관리자',
        'admin@example.com',
        'admin_nick',
        '010-1234-5678',
        DATE '1980-01-01',
        CURRENT_DATE,
        NULL,
        10000,
        'ADMIN',
        'ACTIVATE',
        NULL,
        NULL,
        1);

INSERT INTO users (user_password,
                   user_username,
                   user_name,
                   user_email,
                   nickname,
                   user_phone,
                   user_birth,
                   user_create_at,
                   user_last_login_at,
                   points,
                   user_role,
                   user_state,
                   provider_id,
                   provider_name,
                   grade_id)
VALUES ('$2a$10$gbnVwLK04mxMpf5Za.cbae9DUUqLIEYea1uv18AbKSU.YucNi.BoK',
        '2',
        '유저',
        'admin@example.com',
        'admin_nick',
        '010-1234-5678',
        DATE '1980-01-01',
        CURRENT_DATE,
        NULL,
        10000,
        'USER',
        'ACTIVATE',
        NULL,
        NULL,
        1);